project_id = "lipibykkywbcbsiyywet"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = true

[functions.check-connect-status]
verify_jwt = true

[functions.create-creator-product]
verify_jwt = true
